repos:
- repo: local
  hooks:
    - id: isort
      name: Run isort
      entry: "python -m isort"
      types: [python]
      language: system
    - id: black
      name: Run black
      entry: "python -m black"
      require_serial: true
      types: [python]
      language: system
    - id: pytest
      name: Run pytest
      entry: "python -m pytest tests/unittests"
      language: system
      stages: [push]
      always_run: true
      pass_filenames: false 
